substitutions:
  name: ""
  friendly_name: ""
  room: ""
  wifi_ssid: ""
  wifi_password: ""
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: 'Arlec PC191HA'
  project:
      name: PC191HA
      version: 1.0.0

bk72xx:
  board: wb2s
  framework:
    version: dev

packages:
  # Git repo examples
  remote_package:
    url: https://github.com/esphome/non-existant-repo

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap: 

captive_portal:

logger:

api:

ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://KuzonCode/ESPHome/edit/main/PC191HA.yaml

binary_sensor:
  - platform: gpio
    id: button
    name: 'Button'
    pin:
      number: P11
      inverted: true
    entity_category: "diagnostic"

switch:
  - platform: gpio
    pin: P6
    name: 'Relay'
    id: relay
    internal: True
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - output.turn_on: button_led
    on_turn_off:
      then:
        - switch.turn_on: relay
        - output.turn_on: button_led

output:        # the light in the button
  - platform: gpio
    id: button_led
    pin: P26
#
# PC191HA sensors - power monitoring and wifi signal
#
sensor:
  - platform: hlw8012
    model: BL0937     # note that the model must be specified to use special calculation parameters
    sel_pin:          # I believe that cf_pin reports either Voltage or Current depending on this select pin
      inverted: true  # determine whether true reports Voltage
      number: P24
    cf_pin:           # current or voltage (ele_pin: 7)
      inverted: true  # the logic of BL0937 is opposite from HLW8012
      number: P7
    cf1_pin:          #  Power (vi_pin: 8)
      inverted: true  # the logic of BL0937 is opposite from HLW8012
      number: P8

    update_interval: 1s      # How often to measure and report values

    # PC191HA measures and returns Voltage OR Current according to the value of sel_pin,
    #   but it can change the value of sel_pin periodically  
    initial_mode: "VOLTAGE"       # reports VOLTAGE or CURRENT
    change_mode_every: 4          # how many times to report before swapping between
        #   reporting Voltage or Current. Note that the first value reported should be ignored as inaccurate

    # Adjust according to the actual resistor values on board to calibrate the specific unit
    voltage_divider:  775     # LOWER VALUE GIVES LOWER VOLTAGE
    current_resistor: 0.0009  # HIGHER VALUE GIVES LOWER WATTAGE

    
    power:
      name: 'Power'
      id: 'power'
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - filter_out: 1
        - skip_initial: 2
    
  - platform: total_daily_energy
    id: 'daily_energy'
    name: 'Daily Energy'
    power_id: 'power'
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001  

  - platform: uptime
    name: Uptime
    id: uptime_total
    update_interval: 30s

  - platform: wifi_signal         # report wi-fi signal strength from this end
    name: WiFi Signal
    id: _wifi_signal
    update_interval: 30s    # how often to report wifi signal strength

time:
  - platform: homeassistant
